# Generated by Django 2.1.1 on 2018-09-21 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bracket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elimination_week', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Contestant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=69)),
                ('last_name', models.CharField(max_length=69)),
                ('elimination_week', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=69)),
                ('last_name', models.CharField(max_length=69)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elimination_week', models.PositiveIntegerField()),
                ('score', models.PositiveIntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BracketApp.Player')),
            ],
        ),
        migrations.AddField(
            model_name='bracket',
            name='contestant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BracketApp.Contestant'),
        ),
        migrations.AddField(
            model_name='bracket',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BracketApp.Player'),
        ),
    ]
