# Generated by Django 2.1.1 on 2019-02-22 05:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Bonuses',
                'ordering': ['player'],
            },
        ),
        migrations.CreateModel(
            name='Bracket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_rank', models.PositiveIntegerField(default=0)),
                ('predicted_elimination', models.PositiveIntegerField(default=0)),
                ('submitted', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['player', 'predicted_rank'],
            },
        ),
        migrations.CreateModel(
            name='Contestant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='John', max_length=69)),
                ('last_name', models.CharField(default='Snow', max_length=69)),
                ('shameful_exit', models.BooleanField(default=False)),
                ('actual_rank', models.PositiveIntegerField(default=69)),
                ('actual_elimination', models.PositiveIntegerField(default=69)),
                ('num_confessionals', models.PositiveIntegerField(default=0)),
                ('num_individual_immunity_wins', models.PositiveIntegerField(default=0)),
                ('num_votes_against', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['season', 'actual_rank'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='John Snow', max_length=69)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(default=69)),
                ('elimination', models.PositiveIntegerField(default=69)),
                ('points_per_contestant_remaining', models.PositiveIntegerField(default=0)),
                ('num_boots', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['elimination'],
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elimination', models.PositiveIntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('cum_score', models.IntegerField(default=0)),
                ('rank', models.PositiveIntegerField(default=0)),
                ('points_back', models.PositiveIntegerField(default=0)),
                ('maximum_points_remaining', models.PositiveIntegerField(default=0)),
                ('player', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='BracketApp.Player')),
            ],
            options={
                'ordering': ['player', 'elimination'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(default='David vs. Goliath', max_length=69)),
                ('premiere', models.DateField(default=django.utils.timezone.now)),
                ('current_elimination', models.PositiveIntegerField(default=0)),
                ('current_season', models.BooleanField(default=False)),
                ('first_scored_elimination', models.PositiveIntegerField(default=1)),
                ('season_pic', models.ImageField(blank=True, upload_to='BracketApp/season_pics')),
            ],
            options={
                'ordering': ['show', '-premiere'],
            },
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Survivor', max_length=69)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, upload_to='BracketApp/profile_pics')),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'UserProfileInfo',
            },
        ),
        migrations.AddField(
            model_name='season',
            name='show',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='BracketApp.Show'),
        ),
        migrations.AddField(
            model_name='point',
            name='season',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='BracketApp.Season'),
        ),
        migrations.AddField(
            model_name='player',
            name='season',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='BracketApp.Season'),
        ),
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='BracketApp.UserProfileInfo'),
        ),
        migrations.AddField(
            model_name='contestant',
            name='season',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='contestants', to='BracketApp.Season'),
        ),
        migrations.AddField(
            model_name='bracket',
            name='contestant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='BracketApp.Contestant'),
        ),
        migrations.AddField(
            model_name='bracket',
            name='player',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='BracketApp.Player'),
        ),
        migrations.AddField(
            model_name='bonus',
            name='most_confessionals',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='q1', to='BracketApp.Contestant'),
        ),
        migrations.AddField(
            model_name='bonus',
            name='most_individual_immunity_wins',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='q2', to='BracketApp.Contestant'),
        ),
        migrations.AddField(
            model_name='bonus',
            name='most_votes_against',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='q3', to='BracketApp.Contestant'),
        ),
        migrations.AddField(
            model_name='bonus',
            name='player',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='BracketApp.Player'),
        ),
    ]
