# Generated by Django 2.1.1 on 2018-09-21 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BracketApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(default='David vs Goliath', max_length=69)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Survivor', max_length=69)),
            ],
        ),
        migrations.RemoveField(
            model_name='bracket',
            name='elimination_week',
        ),
        migrations.RemoveField(
            model_name='contestant',
            name='elimination_week',
        ),
        migrations.RemoveField(
            model_name='score',
            name='elimination_week',
        ),
        migrations.AddField(
            model_name='bracket',
            name='predicted_elimination',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contestant',
            name='actual_elimination',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='elimination',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='first_name',
            field=models.CharField(default='John', max_length=69),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='last_name',
            field=models.CharField(default='Snow', max_length=69),
        ),
        migrations.AlterField(
            model_name='player',
            name='first_name',
            field=models.CharField(default='John', max_length=69),
        ),
        migrations.AlterField(
            model_name='player',
            name='last_name',
            field=models.CharField(default='Snow', max_length=69),
        ),
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='season',
            name='show',
            field=models.ForeignKey(default=69, on_delete=django.db.models.deletion.CASCADE, to='BracketApp.Show'),
        ),
        migrations.AddField(
            model_name='bracket',
            name='season',
            field=models.ForeignKey(default=69, on_delete=django.db.models.deletion.CASCADE, to='BracketApp.Season'),
        ),
        migrations.AddField(
            model_name='contestant',
            name='season',
            field=models.ForeignKey(default=69, on_delete=django.db.models.deletion.CASCADE, to='BracketApp.Season'),
        ),
    ]
