# Generated by Django 2.1.1 on 2019-01-06 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BracketApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bonus',
            options={'ordering': ['player'], 'verbose_name_plural': 'Bonuses'},
        ),
        migrations.AlterModelOptions(
            name='bracket',
            options={'ordering': ['player', 'predicted_rank']},
        ),
        migrations.AlterModelOptions(
            name='score',
            options={'ordering': ['player', 'elimination']},
        ),
        migrations.AlterModelOptions(
            name='userprofileinfo',
            options={'verbose_name_plural': 'UserProfileInfo'},
        ),
        migrations.RemoveField(
            model_name='bonus',
            name='season',
        ),
        migrations.RemoveField(
            model_name='bracket',
            name='season',
        ),
        migrations.RemoveField(
            model_name='score',
            name='season',
        ),
    ]
