# Generated by Django 2.1.1 on 2019-01-07 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BracketApp', '0002_auto_20190106_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='season_pic',
            field=models.ImageField(blank=True, upload_to='BracketApp/season_pics'),
        ),
    ]
