# Generated by Django 2.1.1 on 2018-09-21 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BracketApp', '0002_auto_20180921_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='player',
            name='last_name',
        ),
        migrations.AddField(
            model_name='player',
            name='name',
            field=models.CharField(default='John Snow', max_length=69),
        ),
    ]
