# Generated by Django 2.1.1 on 2018-09-21 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BracketApp', '0003_auto_20180921_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='player',
            field=models.CharField(default='John Snow', max_length=69),
        ),
    ]
