# Generated by Django 2.1.1 on 2018-09-28 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BracketApp', '0004_auto_20180921_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bracket',
            name='season',
            field=models.ForeignKey(default=69, on_delete=django.db.models.deletion.PROTECT, to='BracketApp.Season'),
        ),
        migrations.AlterField(
            model_name='season',
            name='show',
            field=models.ForeignKey(default=69, on_delete=django.db.models.deletion.PROTECT, to='BracketApp.Show'),
        ),
    ]
