# Generated by Django 2.1.1 on 2018-09-29 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BracketApp', '0005_auto_20180928_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='cum_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
