# Generated by Django 2.1.1 on 2019-01-07 11:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BracketApp', '0005_auto_20190107_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bracket',
            name='submitted',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='season',
            name='premiere',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
