# Generated by Django 2.1.1 on 2019-01-07 11:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BracketApp', '0006_auto_20190107_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bracket',
            name='submitted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
