# Generated by Django 2.1.1 on 2018-09-30 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BracketApp', '0006_score_cum_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='eliminated',
            field=models.BooleanField(default=False),
        ),
    ]
