# Generated by Django 2.1.1 on 2018-09-30 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BracketApp', '0007_contestant_eliminated'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='rank',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='actual_elimination',
            field=models.PositiveIntegerField(default=69),
        ),
    ]
