# Generated by Django 2.1.1 on 2019-01-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BracketApp', '0007_auto_20190107_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bracket',
            name='submitted',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
