# Generated by Django 2.1.1 on 2019-02-21 18:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BracketApp', '0008_auto_20190107_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='premiere',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
