# Generated by Django 2.1.1 on 2018-09-30 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BracketApp', '0008_auto_20180930_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='shameful_exit',
            field=models.BooleanField(default=False),
        ),
    ]
