# Generated by Django 2.1.1 on 2018-09-30 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BracketApp', '0009_contestant_shameful_exit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contestant',
            name='eliminated',
        ),
        migrations.AlterField(
            model_name='contestant',
            name='shameful_exit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
