# Generated by Django 2.1.1 on 2019-02-22 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BracketApp', '0009_auto_20190221_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='premiere',
            field=models.DateTimeField(null=True),
        ),
    ]
