# Generated by Django 2.1.1 on 2018-10-01 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BracketApp', '0010_auto_20180930_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='points_back',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
