# Generated by Django 2.1.1 on 2018-10-01 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BracketApp', '0011_score_points_back'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestant',
            name='shameful_exit',
            field=models.BooleanField(default=False),
        ),
    ]
