# Generated by Django 2.1.1 on 2018-10-02 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BracketApp', '0012_auto_20180930_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='contestant',
            name='num_confessionals',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contestant',
            name='num_individual_immunity_wins',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contestant',
            name='num_votes_against',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bonus',
            name='most_confessionals',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='q1', to='BracketApp.Contestant'),
        ),
        migrations.AddField(
            model_name='bonus',
            name='most_individual_immunity_wins',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='q2', to='BracketApp.Contestant'),
        ),
        migrations.AddField(
            model_name='bonus',
            name='most_votes_against',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='q3', to='BracketApp.Contestant'),
        ),
        migrations.AddField(
            model_name='bonus',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BracketApp.Player'),
        ),
        migrations.AddField(
            model_name='bonus',
            name='season',
            field=models.ForeignKey(default=69, on_delete=django.db.models.deletion.PROTECT, to='BracketApp.Season'),
        ),
    ]
