# Generated by Django 2.1.1 on 2018-10-02 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BracketApp', '0013_auto_20181002_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='current_elimination',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='season',
            name='subtitle',
            field=models.CharField(default='David vs. Goliath', max_length=69),
        ),
    ]
