# Generated by Django 2.1.1 on 2018-10-02 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BracketApp', '0014_auto_20181002_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='bracket',
            name='predicted_rank',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contestant',
            name='actual_rank',
            field=models.PositiveIntegerField(default=69),
        ),
    ]
