# Generated by Django 2.1.1 on 2018-10-02 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BracketApp', '0015_auto_20181002_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='current_season',
            field=models.BooleanField(default=False),
        ),
    ]
