# Generated by Django 2.1.1 on 2018-10-03 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BracketApp', '0016_season_current_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='first_scored_elimination',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
