# Generated by Django 2.1.1 on 2018-10-05 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BracketApp', '0017_season_first_scored_elimination'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='season',
            field=models.ForeignKey(default=69, on_delete=django.db.models.deletion.PROTECT, to='BracketApp.Season'),
        ),
        migrations.AlterField(
            model_name='score',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BracketApp.Player'),
        ),
    ]
