# Generated by Django 2.1.1 on 2018-10-05 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BracketApp', '0018_auto_20181005_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestant',
            name='season',
            field=models.ForeignKey(default=69, on_delete=django.db.models.deletion.PROTECT, to='BracketApp.Season'),
        ),
    ]
