# Generated by Django 2.1.1 on 2018-10-07 22:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BracketApp', '0020_auto_20181005_2212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bonus',
            options={'ordering': ['season', 'player'], 'verbose_name_plural': 'Bonuses'},
        ),
        migrations.AlterModelOptions(
            name='bracket',
            options={'ordering': ['season', 'player', 'predicted_rank']},
        ),
        migrations.AlterModelOptions(
            name='contestant',
            options={'ordering': ['season', 'actual_rank']},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='score',
            options={'ordering': ['season', 'player', 'elimination']},
        ),
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ['show', 'subtitle']},
        ),
        migrations.AlterModelOptions(
            name='show',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='season',
            name='premiere',
            field=models.DateField(default=datetime.datetime(2018, 10, 7, 15, 17, 48, 351959)),
        ),
    ]
