# Generated by Django 2.1.1 on 2018-10-08 02:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BracketApp', '0021_auto_20181007_1517'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ['show', '-premiere']},
        ),
        migrations.AddField(
            model_name='player',
            name='season',
            field=models.ManyToManyField(to='BracketApp.Season'),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='season',
            field=models.ForeignKey(default=69, on_delete=django.db.models.deletion.PROTECT, related_name='contestants', to='BracketApp.Season'),
        ),
        migrations.AlterField(
            model_name='season',
            name='premiere',
            field=models.DateField(default=datetime.datetime(2018, 10, 7, 19, 53, 25, 255361)),
        ),
    ]
