# Generated by Django 2.1.1 on 2018-10-08 02:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BracketApp', '0022_auto_20181007_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='premiere',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
