# Generated by Django 2.1.1 on 2018-10-08 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BracketApp', '0023_auto_20181007_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='maximum_points_remaining',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bracket',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BracketApp.Season'),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contestants', to='BracketApp.Season'),
        ),
    ]
